# Generated by Django 4.1.2 on 2022-10-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionWorkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributedName', models.CharField(blank=True, default='Null Name', max_length=100, null=True)),
                ('contributedWorkImage', models.ImageField(default='image_21.jpeg', upload_to='images-work-contrib/')),
                ('contributedWorkDescription', models.TextField(blank=True, default='enter description', null=True)),
                ('contributedLink', models.URLField(default='https://github.com/abhinav1590')),
            ],
            options={
                'verbose_name': 'CONTRIBUTED WORK PAGE',
            },
        ),
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experties', models.CharField(max_length=200)),
                ('Introduction', models.TextField()),
            ],
            options={
                'verbose_name': 'HOME PAGE',
            },
        ),
        migrations.CreateModel(
            name='PersonalWorkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalName', models.CharField(blank=True, max_length=50, null=True)),
                ('personalWorkImage', models.ImageField(default=' image_21.jpeg', upload_to='images-work/')),
                ('personalWorkDescription', models.TextField(blank=True, null=True)),
                ('personalLink', models.URLField(default='https://github.com/abhinav1590')),
            ],
            options={
                'verbose_name': 'PERSONAL WORK PAGE',
            },
        ),
        migrations.CreateModel(
            name='PhotographyWorkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPhotoName', models.CharField(blank=True, max_length=50, null=True)),
                ('userPhotoDescription', models.TextField(default='Add description / quote ')),
                ('userPhoto', models.ImageField(default='image_21.jpeg', upload_to='image-photography/')),
            ],
            options={
                'verbose_name': 'PHOTOGRAPHY PAGE',
            },
        ),
        migrations.CreateModel(
            name='UserAboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Image', models.ImageField(default=' image_21.jpeg', upload_to='images/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': ' ABOUT PAGE',
            },
        ),
    ]
