# Generated by Django 4.1.2 on 2022-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abhinav', '0003_remove_homepagemodel_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='UserVideo',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
