# Generated by Django 4.1.2 on 2022-11-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abhinav', '0006_homepagemodel_userwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='UserReach',
            field=models.ImageField(null=True, upload_to='image-bitmoji'),
        ),
        migrations.AddField(
            model_name='homepagemodel',
            name='workIntroduction',
            field=models.TextField(default='enter work', max_length=100),
        ),
    ]
