# Generated by Django 4.1.2 on 2022-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abhinav', '0007_homepagemodel_userreach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagemodel',
            name='workIntroduction',
            field=models.TextField(default='enter work'),
        ),
    ]
